openapi: 3.0.4
info:
  title: Text Styler
  description: Text Styler is a simple tool for styling text in various ways. It returns the styled text.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/textstyler:
    post:
      summary: Style Text in Bubbles
      description: Text Styler is a simple tool for styling text in various ways. It returns the styled text.
      operationId: textstyler
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  style: bubbles
                  text: Ⓣⓗⓘⓢ ⓘⓢ ⓐ ⓥⓔⓡⓨ ⓢⓣⓨⓛⓘⓢⓗ ⓟⓘⓔⓒⓔ ⓞⓕ ⓣⓔⓧⓣ
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: 'The style you want to apply to the text. Allowed styles: strikeThrough, wingdings, vaporwave, typewriter, analucia, tildeStrikeThrough, underline, doubleUnderline, slashThrough, sparrow, heartsBetween, arrowBelow, crossAboveBelow, creepify, bubbles, mirror, squares, roundsquares, flip, tiny'
                  example: This is a very stylish piece of text
                style:
                  type: string
                  description: 'The style you want to apply to the text. Allowed styles: strikeThrough, wingdings, vaporwave, typewriter, analucia, tildeStrikeThrough, underline, doubleUnderline, slashThrough, sparrow, heartsBetween, arrowBelow, crossAboveBelow, creepify, bubbles, mirror, squares, roundsquares, flip, tiny'
                  example: bubbles
              required:
              - text
              - style
              example:
                text: This is a very stylish piece of text
                style: bubbles
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
